services:
  unifi:
    image: goofball222/unifi:8.6
    container_name: unifi
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "cert:/usr/lib/unifi/cert/"
      - "data:/usr/lib/unifi/data/"
      - "logs:/usr/lib/unifi/logs/"
      - "config:/usr/lib/unifi/data/sites/"
    restart: always
    networks:
      proxy:
    dns:
      - ${DNS_IP1}
      # - ${DNS_IP2}
    dns_search: ${DOMAIN}
    ports:
      - 3478:3478/udp
      - 8080:8080
      - 8443:8443
      - 8880:8880
      - 8843:8843
#     Optional: Uncomment to enable speed tests from the UniFi iOS & Android apps
      - 6789:6789
#     Optional: Uncomment for layer 2 broadcast discovery if container running on a host in the local LAN
      - 10001:10001/udp
    environment: 
      TZ: UTC
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.unifi.rule=Host(`unifi.${DOMAIN}`)"
      - "traefik.http.services.unifi.loadbalancer.server.port=8443"
      - "traefik.http.routers.unifi.entrypoints=websecure"
      - "traefik.http.routers.unifi.tls.certresolver=le_dns"

networks:
  proxy:
    external: true

volumes:
  cert:
  data:
  logs:
  config: